export const dashboardTour = [
  {
    element: "#kpi-plants",
    popover: {
      title: "Plants",
      description: "Total number of plants registered in your manufacturing system.",
      position: "bottom",
    },
  },

  {
    element: "#kpi-departments",
    popover: {
      title: "Departments",
      description: "Departments inside each plant. This helps in understanding the structure.",
      position: "bottom",
    },
  },

  {
    element: "#kpi-assets",
    popover: {
      title: "Total Assets",
      description: "All assets across all plants and departments.",
      position: "bottom",
    },
  },

  {
    element: "#kpi-devices",
    popover: {
      title: "Devices",
      description: "Live connected devices and offline devices (admin only).",
      position: "bottom",
    },
  },

  {
    element: "#kpi-alerts",
    popover: {
      title: "Alerts Today",
      description: "Shows real-time alerts generated by devices today.",
      position: "bottom",
    },
  },

  {
    element: "#stat-uptime",
    popover: {
      title: "System Uptime",
      description: "Shows uptime percentage of the entire system.",
      position: "top",
    },
  },
  {
    element: "#stat-efficiency",
    popover: {
      title: "Efficiency",
      description: "Plant performance efficiency based on last calculations.",
      position: "top",
    },
  },
  {
    element: "#stat-response",
    popover: {
      title: "Avg Response Time",
      description: "Average device-to-server communication delay.",
      position: "top",
    },
  },
  {
    element: "#stat-critical",
    popover: {
      title: "Critical Issues",
      description: "Shows critical alerts that need immediate attention.",
      position: "top",
    },
  },

  {
    element: "#chart-device-status",
    popover: {
      title: "Device Status Chart",
      description: "Visual representation of active and offline devices.",
      position: "right",
    },
  },

  {
    element: "#chart-performance",
    popover: {
      title: "Performance Metrics",
      description: "Shows performance stats for the past 8 hours.",
      position: "left",
    },
  },
];
